name = "backend"
main = "src/index.ts"
compatibility_date = "2024-01-30"
compatibility_flags = ["nodejs_compat"]


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWE1BWldGUThZVkpRQzhTVlRWOUs4TVgiLCJ0ZW5hbnRfaWQiOiJmMmE1YmYxN2FhYjY4Yjk2NzNjNzA2YWNjMDdhZmNkNmNkYmEyNjM2NzdkYzlmNmIxM2E3MmIxNzZiMDlhZTM3IiwiaW50ZXJuYWxfc2VjcmV0IjoiZGFiZjczMjctMmQ0NC00YjYwLWI5N2QtODBiOWIyOTRhNTZjIn0.Qyql-EZgbLwH_tmPwGwYGAWXBVjWc4bWZW838J3sezM"
JWT_SECRET="Murali222"
NODE_ENV="development"
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="dvtraesvv"
CLOUDINARY_API_KEY="213712663377536"
CLOUDINARY_API_SECRET="sIa8MnsgUEGx-xKHwQFondYe1wg"